import type { Deal, Product } from './types';

export const initialDeals: Deal[] = [
  {
    _id: '1',
    title: '50% Off All Electronics',
    description: 'Upgrade your tech with half-price deals on laptops, headphones, and more. Limited time only!',
    category: 'Electronics',
    expires: 'in 3 days',
  },
  {
    _id: '2',
    title: 'Buy One Get One Free on T-Shirts',
    description: 'Stock up on your favorite styles. Mix and match any two t-shirts and get one for free.',
    category: 'Apparel',
    expires: 'this week',
  },
  {
    _id: '3',
    title: '$100 Off Home Appliances',
    description: 'From blenders to vacuums, save big on essential home appliances.',
    category: 'Home Goods',
    expires: 'in 5 days',
  },
  {
    _id: '4',
    title: 'Clearance on All Winter Gear',
    description: 'Get ready for next year with up to 70% off on all winter jackets, boots, and accessories.',
    category: 'Seasonal',
    expires: 'while supplies last',
  },
  {
    _id: '5',
    title: '20% Off All Groceries',
    description: 'Fill your pantry and save. Discount applied at checkout.',
    category: 'Groceries',
    expires: 'today only',
  },
  {
    _id: '6',
    title: 'Special Bundle: Gaming Console + 2 Games',
    description: 'Get the latest gaming console bundled with two blockbuster titles for one low price.',
    category: 'Gaming',
    expires: 'in 2 days',
  },
];

export const dummyProducts: Product[] = [
  {
    _id: 'prod_1',
    name: 'Classic Cotton T-Shirt',
    slug: 'classic-cotton-t-shirt',
    categorySlug: 'apparel',
    price: 24.99,
    imageUrl: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=800&q=60',
    description: 'A timeless, comfortable t-shirt made from 100% premium cotton. Perfect for everyday wear.',
    featured: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: 'prod_2',
    name: 'Wireless Noise-Cancelling Headphones',
    slug: 'wireless-noise-cancelling-headphones',
    categorySlug: 'electronics',
    price: 199.99,
    imageUrl: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=800&q=60',
    description: 'Immerse yourself in sound with these high-fidelity, noise-cancelling headphones. 30-hour battery life.',
    featured: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: 'prod_3',
    name: 'Modern Ceramic Vase',
    slug: 'modern-ceramic-vase',
    categorySlug: 'home-goods',
    price: 49.99,
    imageUrl: 'https://images.unsplash.com/photo-1578996953843-0917d235a862?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=800&q=60',
    description: 'A beautifully crafted minimalist vase to elevate any room. Available in matte white or black.',
    featured: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: 'prod_4',
    name: 'Organic Whole Bean Coffee',
    slug: 'organic-whole-bean-coffee',
    categorySlug: 'groceries',
    price: 18.50,
    imageUrl: 'https://images.unsplash.com/photo-1559449262-5a15a03b5478?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=800&q=60',
    description: 'A rich, full-bodied medium roast coffee, ethically sourced from Central America. 12oz bag.',
    featured: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: 'prod_5',
    name: 'The Alchemist\'s Secret',
    slug: 'the-alchemists-secret',
    categorySlug: 'books',
    price: 14.95,
    imageUrl: 'https://images.unsplash.com/photo-1544947950-fa07a98d237f?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=800&q=60',
    description: 'A thrilling mystery novel that will keep you on the edge of your seat until the very last page.',
    featured: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: 'prod_6',
    name: 'Pro-Grade Gaming Mouse',
    slug: 'pro-grade-gaming-mouse',
    categorySlug: 'gaming',
    price: 79.99,
    imageUrl: 'https://images.unsplash.com/photo-1563297007-162a82a83213?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=800&q=60',
    description: 'Ultra-lightweight, ergonomic design with a high-precision 16,000 DPI sensor for competitive gaming.',
    featured: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: 'prod_7',
    name: 'All-Weather Performance Jacket',
    slug: 'all-weather-performance-jacket',
    categorySlug: 'seasonal',
    price: 120.00,
    imageUrl: 'https://images.unsplash.com/photo-1591241334543-7a9543c4aa86?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=800&q=60',
    description: 'Waterproof, windproof, and breathable. This jacket is built to handle any adventure, rain or shine.',
    featured: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: 'prod_8',
    name: 'Smart LED Light Strip',
    slug: 'smart-led-light-strip',
    categorySlug: 'electronics',
    price: 34.99,
    imageUrl: 'https://images.unsplash.com/photo-1623944883944-143d4d84107e?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=800&q=60',
    description: 'Transform your space with millions of colors. Controllable via app and voice assistants. 2-meter strip.',
    featured: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: 'prod_9',
    name: 'Leather Messenger Bag',
    slug: 'leather-messenger-bag',
    categorySlug: 'apparel',
    price: 149.99,
    imageUrl: 'https://images.unsplash.com/photo-1519680383265-f0955198978e?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=800&q=60',
    description: 'Handcrafted from full-grain leather, this bag combines style and durability. Fits up to a 15-inch laptop.',
    featured: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: 'prod_10',
    name: 'Stainless Steel Water Bottle',
    slug: 'stainless-steel-water-bottle',
    categorySlug: 'home-goods',
    price: 29.99,
    imageUrl: 'https://images.unsplash.com/photo-1602143407151-247e96143834?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=800&q=60',
    description: 'Keep your drinks cold for 24 hours or hot for 12. BPA-free and eco-friendly. 25oz capacity.',
    featured: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: 'prod_11',
    name: 'Gourmet Olive Oil',
    slug: 'gourmet-olive-oil',
    categorySlug: 'groceries',
    price: 22.00,
    imageUrl: 'https://images.unsplash.com/photo-1625704343333-d3d659622946?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=800&q=60',
    description: 'Extra virgin olive oil, cold-pressed from hand-picked Italian olives. Perfect for salads and cooking.',
    featured: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: 'prod_12',
    name: 'The Art of Strategy',
    slug: 'the-art-of-strategy',
    categorySlug: 'books',
    price: 24.95,
    imageUrl: 'https://images.unsplash.com/photo-1592496431122-2349e0fbc666?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=800&q=60',
    description: 'A modern take on classic strategic principles, applicable to business, life, and everything in between.',
    featured: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  }
];
